### ISSUE TITLE
Refactor go code into packages where applicable

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#10]
Some processing elements can get pulled out and placed into a self contained go package. We should do this where ever possible to encourage code modularity and cleanliness.

**Comment by cpjolicoeur** [comment]
I'll tackle this if you want.  It's going to take a bit of work and moving things around, but if you want I'll tackle it.

**Comment by regexb** [comment]
That would be awesome :+1:

**Comment by regexb** [comment]
@cpjolicoeur Can we move the templates parser into a sub package so I can use it for the mock server?

**Comment by cpjolicoeur** [comment]
What is the mock server?  And why can't you use it from the current package?  `feedbag.ParseTemplateDir(...)`?

**Comment by regexb** [comment]
A mock version of the feedbag api so frontend devs can just run the compiled binary (without any setup, github app, or go knowledge) and gulp. https://github.com/begizi/feedbag-mock-api

**Comment by regexb** [comment]
Is there anywhere else we would want to move code into sub packages?

**Comment by regexb** [comment]
Closing ticket for now.
