### ISSUE TITLE
Directory Structure

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#12]
I'd like to open a thread about how to structure this app for clean, friendly development. @sethkrasnianski recommended separating the server and client files into separate directories. I think this is a good idea as it would be less intimidating for people unfamiliar with go to come in and see the root littered with go packages and files. However, the build structure will have to stay the same with the compiled binary at the root and a `templates` and `public`. 

With that in mind, what if we nest all of the development files into a `src` directory containing the folders `server` and `client`? We would have a `build` directory in the root as well where we would put the releases containing the compiled binary, templates, and web assets.

**Comment by regexb** [comment]
Example:

```
.
├── build.sh
├── build
│   ├── bin
│   ├── public
│   └── templates
└── src
    ├── client
    └── server
```

**Comment by regexb** [comment]
@cpjolicoeur Any input on this? I have a pending PR #19 to implement this.

**Comment by cpjolicoeur** [comment]
I dont think we want to move the go source out of root.  If people are intimidated, tough, they will have to get used to it.  This is a go project, so they should get familiar with go.  If we move the go code out of root we break the ability to "go get" the project and a few other things.

**Comment by regexb** [comment]
I've been having running both goconvey and looper when the code is in the root because it tries to add watchers on all of the files in the web directory. Have you had this issue?

**Comment by cpjolicoeur** [comment]
What is wrong with the current `web/` directory you currently have?  Rename it to `client` or something if that is more "front-end" familiar, but I dont see much wrong with the currently layout personally

**Comment by cpjolicoeur** [comment]
I think you missed a word or phrase there?  You've "been having running both...." what? having what?  issues? errors? It will add watchers, but the default for both tools is to watch only files ending in `.go`.

I know goconvey allows configuring both extra file and whole directly exclusion rules.

**Comment by sethkrasnianski** [comment]
I'd like to add that my recommendation was not caused by intimidation. 
Mainly two reasons:
1. Most every web application that I've worked with / investigated code for (that considers a logical directory structure for all contributors) separates the front end interface from the back end interface. Almost exactly how @begizi suggested.
2. Every open source go application (web or not) utilizes a similar structure.

I'm not saying we need to be like everyone else, but if logical directory patterns are used in many applications elsewhere then there's a necessity / reason for it. 

You hardly see projects with source files in root anyway. Lets go for something like this, even if it's not exactly what @begizi proposed.

**Comment by sethkrasnianski** [comment]
I'm sure we can adjust some things for go get to work and hopefully anything else that you suggested may break

**Comment by sethkrasnianski** [comment]
Or potentially have an entry file, `main.go` or `app.go` in root that requires all `src/server` files.

**Comment by cpjolicoeur** [comment]
Project structure is, of course by nature, very language specific.  Java has a certain layout, as does Ruby, and C.  The norm for C and Go is that the files for the `main` package reside in the project root, and sub packages live in sub-directories that are named according to the package name.

I'm all for having a front-end directory, whether that be `client` or `web` or whatever it be named.  In that directory all the client files, build scripts, manifests, etc.. can/should reside.

My point was that this _is_ the preferred normal directory structure for Go based applications.

**Comment by cpjolicoeur** [comment]
The number of top-level `*.go` files will be reduced soon when we move some code out of the `main` package and into sub packages, but there will (or should) also be one (or a few) top-level go files there.

**Comment by regexb** [comment]
What would be the use case for a user needing to "go get" the repo? I know we have a few pieces we can be pulled out into separate packages but can't we make separate repos for these components?

**Comment by sethkrasnianski** [comment]
I've seen countless go projects that _don't_ house all `.go` files in root though.

**Comment by cpjolicoeur** [comment]
agreed, the files related to the `main` package are in root tho, thats all I'm saying

**Comment by sethkrasnianski** [comment]
> The number of top-level *.go files will be reduced soon when we move some code out of the main package and into sub packages, but there will (or should) also be one (or a few) top-level go files there.

Agreed that's probably all we need then.

**Comment by cpjolicoeur** [comment]
@begizi A user can `go get github.com/mojotech/feedbag` and then just run the app?  `go get` is a built in delivery mechanism of the final product in addition to them downloading binaries directly from us if they wanted.

**Comment by cpjolicoeur** [comment]
@sethkrasnianski Do you have any links to those go projects you are talking about?  I'd be curious to see them and what their layout is.

**Comment by regexb** [comment]
I think I would be ok leaving the directories how we have them now. I imagine it should get a lot cleaner once we add more sub packages for certain components

**Comment by regexb** [comment]
It's only for development anyway. The final build directory will only have the single compiled binary and 2 folders: `Templates`, and `Client`

**Comment by cpjolicoeur** [comment]
I guess I also don't personally think it's "not clean" now.  We have go files, and we have a web directory (which to me is where all the code and files related to web stuff are)

**Comment by regexb** [comment]
Let's leave the directory structure as it is now and revisit if/when the codebase grows to an unmanageable size. Let's classify this thread as a premature optimization debate.

**Comment by sethkrasnianski** [comment]
Sure, some projects. Not necessarily web apps

Prometheus - https://github.com/prometheus/prometheus
NSQ -https://github.com/bitly/nsq
docket - https://github.com/netvarun/docket
kubernetes -https://github.com/GoogleCloudPlatform/kubernetes
hugo - https://github.com/spf13/hugo
ImgurGo https://github.com/gophergala/ImgurGo - supports what you said, @cpjolicoeur about main package files in root.

**Comment by cpjolicoeur** [comment]
Thanks for the links.  So the majority of those do have the `main` package file in the root like you mentioned, and then have most of their code as sub-packages.

Some of them that have no go files in the root, are meant only to be used for their individual sub-packages.  You don't use any kind of `main` package from those projects directly, you only import and use the sub-packages individually.
