### ISSUE TITLE
Config file for github app tokens and more

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#13]
I'm inclined to say we should add in this config file sooner rather than later. I still think we should prioritize config options from environment variables, but I think people would like the option to put them into a config file instead. 

The config file would also tell go what directories to serve static assets from, what port to run on, and maybe what level of logging to write to stdout (we can implement https://godoc.org/github.com/tideland/goas/v3/logger if we can agree this would be a nice feature to have).

**Comment by cpjolicoeur** [comment]
Keys and things should be ENV vars for sure.  Where to serve templates, static assets, port and host, and those other things should be a flag to the go binary when you run it.  In a "real world" installation, the go binary would be behind something like nginx and nginx would serve the static assets direct with those requests never hitting the go bin.

**Comment by cpjolicoeur** [comment]
Of course, github keys could also be flags to the binary, I'm saying the default should be ENV vars for those

**Comment by regexb** [comment]
That's pretty much how we have it now. I'll add in the optional flags for the keys but have the ENV var take precedent.

What are your thoughts about adding a logging library like the one mentioned?

**Comment by cpjolicoeur** [comment]
Yeah, there are plenty of loggers, we can pick one.  What are we really needing to log at different levels tho?  Most logging for now was just for dev debugging, right?  It cant hurt tho to have one

**Comment by regexb** [comment]
I think it would be useful to have 2 log modes, verbose and production. Verbose would help with debugging and checking up on what the system is doing. Production would just report errors and important messages that the installer might care about.

**Comment by cpjolicoeur** [comment]
well, we would log using the standard log levels of DEBUG, INFO, WARN, ERROR, FATAL but I get what you are saying.  Dev just sets their flag to DEBUG and production can set the flag to ERROR or FATAL depending on what they want to see

**Comment by regexb** [comment]
Closing until we have a need for a separate config file. Maybe when we add in #29
