### ISSUE TITLE
Re-implement Github Oauth2 authentication

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#14]
The current library we are using doesn't yet support `scope` during the authentication request. This limits our app to only fetch the public activity.

Given that we only need Github as an oauth provider, we should switch to just use the go-supported oauth2 library.

**Comment by cpjolicoeur** [comment]
I did add scope support to [Goth](https://github.com/markbates/goth/pull/21) so we can either switch to using that or Oauth2.  I'll tackle this though either way.
