### ISSUE TITLE
Frontend discussion

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#2]
Looking for ideas/recommendations for a frontend framework.

Right now, a severely incomplete and poorly designed angular frontend is in place and either needs a lot of work, or for someone to re-write it in a different technology.

Any thoughts? Takers?

**Comment by cpjolicoeur** [comment]
What are the intentions for front-end functionality? I think the final desired output determines a lot of which frameworks are best to use.  

It sounds like this really isn't an "application" per se, but more that there will be a page or two where users can configure some settings, but the interaction on the front-end beyond that is limited right?

**Comment by regexb** [comment]
I agree that a framework is overkill. After thinking about it for a while, we should really keep the client as light as possible. I do still think we will largely benefit from using a css pre-processor, concatenation, and minification. Coffeescript will be more of a convenience, but worth adding in since we need a build process for the css pre-processor anyway.

**Comment by cpjolicoeur** [comment]
I'm not suggesting using a framework isnt the right way to go, it just seemed like, at first glance, tons of stuff was added.  Even if a full blown front-end framework isn't added, using a view manager like Backbone or React would probably make more sense than hand-coding everything.

The front-end build process should be reproducible and automated, so there is no getting around a build tool.  I didn't realize at first until you said it, that all that was thrown in by the yoeman generator by default.  I'd be inclined to just add the build plugins required to cut down on what users need to install on their system to get going.

**Comment by regexb** [comment]
Decided to go to Backbone with Handlebars templates. Will be using the isotope library for the grid layout.
