### ISSUE TITLE
The templates should be be able to parse Markdown into HTML

### ISSUE THREAD

**Issue by zachgibb** [mojotech/feedbag#56]

**Comment by regexb** [comment]
You want to take this one on @bighazycrab?

**Comment by zachgibb** [comment]
yup

**Comment by zachgibb** [comment]
forgot to assign myself

**Comment by zachgibb** [comment]
:smile_cat:

**Comment by cpjolicoeur** [comment]
I'm not understanding why we'd want this?  Markdown is intended for natural-language style writing to easily be converted to HTML pages.  It doesnt support things like classes, and interpolations and things like that that would be needed in a template markup?

**Comment by regexb** [comment]
We get the raw markdown from the github events. We are just parsing the markdown to display the event content the same way it appears on github.

**Comment by regexb** [comment]
Example in use https://github.com/mojotech/feedbag/blob/zg/markdown_parsing/templates/create_issue_comment.tmpl#L10

**Comment by regexb** [comment]
closed by #59
