### ISSUE TITLE
Move templates to endpoint

### ISSUE THREAD

**Issue by regexb** [mojotech/feedbag#6]
Right now, the templates are getting injected into the index.html page. This should be changed so that a `/templates` endpoint is exposed that returns a json array of templates and their ids.

**Comment by cpjolicoeur** [comment]
What is the win we get for doing it this way instead of direct injection system? Just curious/

**Comment by regexb** [comment]
Isolation between the client and server components. This will allow us to develop the frontend without the dependency on running the go server. It will also allow a client to be written to use the server without the need for templates at all.

**Comment by cpjolicoeur** [comment]
Is the intention to still parse/load the templates on app start, or should the directory be re-parsed anytime the `/templates` endpoint is hit to allow for dynamically adding new templates without restarting the binary?

**Comment by regexb** [comment]
I would say we can re-parse them when the endpoint it hit. I wouldn't really worry about a longer blocking operation at this point because the client will most likely startup and run for long periods of time
